export const projects = [
  {
    id: 1,
    title: "Math Challenge",
    image: "Images/math img.png",
    description:
      "Interactive math game featuring multiple difficulty levels and real-time scoring.",
    link: "./Projects/math-challenge/math.html",
    download: "./Downloads/math-challenge.rar",
    tags: ["JavaScript", "Math", "Game"],
    technologies: ["HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 2,
    title: "Hangman Game",
    image: "Images/hangMan.png",
    description: "Classic word guessing game with extensive word database.",
    link: "Projects/HangMan Game/hangman.html",
    download: "./Downloads/HangMan Game.rar",
    tags: ["JavaScript", "Game", "Words"],
    technologies: ["HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 3,
    title: "Pokemon Project",
    image: "Images/Pokemon.png",
    description:
      "Comprehensive Pokemon database with search and filtering capabilities.",
    link: "Projects/Pokemon Project/pokemon.html",
    download: "./Downloads/Pokemon Project.rar",
    tags: ["API", "Pokemon", "Database"],
    technologies: ["HTML5", "CSS3", "JavaScript", "REST API"],
  },
  {
    id: 4,
    title: "Snake Game",
    image: "Images/snakee.png",
    description:
      "Modern implementation of the classic Snake game with special features and power-ups.",
    link: "Projects/Snake Game/snake.html",
    download: "./Downloads/Snake Game.rar",
    tags: ["JavaScript", "Game", "Retro"],
    technologies: ["HTML5", "Canvas", "JavaScript"],
  },
  {
    id: 5,
    title: "Screen Builder",
    image: "Images/screen Img.png",
    description:
      "Visual tool for creating screen layouts with drag-and-drop functionality.",
    link: "Projects/screen-builder/screen.html",
    download: "./Downloads/screen-builder.rar",
    tags: ["UI", "Design", "Tool"],
    technologies: ["HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 6,
    title: "Countries API",
    image: "Images/countries.png",
    description: "Explore country information using REST API.",
    link: "Projects/Contries Porject/countries.html",
    download: "./Downloads/Contries Porject.rar",
    tags: ["API", "Countries", "Database"],
    technologies: ["HTML5", "CSS3", "JavaScript", "REST API"],
  },
  {
    id: 7,
    title: "Tic-Tac-Toe Game",
    image: "Images/tic-tac-toe.png",
    description:
      "A classic Tic-Tac-Toe game with three difficulty levels and score tracking.",
    link: "Projects/Tic-Tac-Toe/tic-tac-toe.html",
    download: "./Downloads/Tic-Tac-Toe.rar",
    tags: ["Game", "AI", "Minimax"],
    technologies: ["HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 8,
    title: "Code Master Quiz",
    image: "Images/code-master.png",
    description:
      "A programming quiz game based on 'Who Wants to Be a Millionaire' with 15 progressive JavaScript questions and lifelines.",
    link: "Projects/Code-Master/code-master.html",
    download: "./Downloads/Code-Master.rar",
    tags: ["Game", "Quiz", "Educational"],
    technologies: ["HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 9,
    title: "Memory Card Game",
    image: "Images/memory-card-game.png",
    description:
      "A fun and challenging memory card game where players match pairs of cards. Features multiple difficulty levels, a timer, and a high score system.",
    link: "Projects/Memory Game/index.html",
    download: "./Downloads/Memory-Card-Game.rar",
    tags: ["Game", "Memory", "Educational"],
    technologies: ["HTML5", "CSS3", "JavaScript"],
  },
];
